name: Practice
version: ${project.version}
main: tk.whitelauncher.practice.Practice
api-version: 1.15.2
authors: [Loulou30140]
website: whitelauncher.tk
commands:
  help:
    description: Submit help command
    aliases: [aide, ?]
  duel:
    description: Duel command
    aliases: [d, defi]
